name: Package and Publish VS Code Extension

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      # SonarCloud Quality Check Step
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          sonarToken: ${{ secrets.SONAR_TOKEN }}
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install vsce
        run: npm install -g vsce

      - name: Check current version vs marketplace version
        id: check-version
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          MARKETPLACE_VERSION=$(vsce show Corgi.corgi --json | grep -m1 '"version":' | awk -F'"' '{print $4}')

          if [ "$CURRENT_VERSION" == "$MARKETPLACE_VERSION" ]; then
            echo "Version $CURRENT_VERSION is already published"
            echo "VERSION_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Version $CURRENT_VERSION is not yet published"
            echo "VERSION_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Publish to Visual Studio Marketplace
        if: github.ref == 'refs/heads/main' && env.VERSION_EXISTS == 'false'
        run: make publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
