name: Package and Publish VS Code Extension

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Install vsce
        run: npm install -g vsce

      - name: Check current version vs marketplace version
        id: check-version
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          MARKETPLACE_VERSION=$(vsce show Corgi.corgi --json | grep -m1 '"version":' | awk -F'"' '{print $4}')
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

          if [ "$CURRENT_VERSION" == "$MARKETPLACE_VERSION" ]; then
            echo "Version $CURRENT_VERSION is already published"
            echo "VERSION_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Version $CURRENT_VERSION is not yet published"
            echo "VERSION_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Package Extension
        if: env.VERSION_EXISTS == 'false'
        run: pnpm build:vsce

      - name: Publish to Visual Studio Marketplace
        if: env.VERSION_EXISTS == 'false'
        run: make publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Generate Changelog
        if: env.VERSION_EXISTS == 'false'
        id: generate-changelog
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ ! -z "$LATEST_TAG" ]; then
            CHANGELOG=$(git log --pretty=format:"- %s" $LATEST_TAG..HEAD)
            echo "CHANGELOG=$CHANGELOG" >> $GITHUB_ENV
          else
            echo "No previous tags found."
          fi

      - name: Create GitHub Release
        if: env.VERSION_EXISTS == 'false'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.CURRENT_VERSION }}
          release_name: Release ${{ env.CURRENT_VERSION }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Release Asset
        if: env.VERSION_EXISTS == 'false'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./corgi-${{ env.CURRENT_VERSION }}.vsix
          asset_name: corgi-${{ env.CURRENT_VERSION }}.vsix
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
